#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_1.mp4" --output "data/Track1/Loc1_1/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_2.mp4" --output "data/Track1/Loc1_2/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_3.mp4" --output "data/Track1/Loc1_3/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_4.mp4" --output "data/Track1/Loc1_4/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_5.mp4" --output "data/Track1/Loc1_5/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_6.mp4" --output "data/Track1/Loc1_6/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_7.mp4" --output "data/Track1/Loc1_7/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc1_8.mp4" --output "data/Track1/Loc1_8/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_1.mp4" --output "data/Track1/Loc2_1/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_2.mp4" --output "data/Track1/Loc2_2/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_3.mp4" --output "data/Track1/Loc2_3/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_4.mp4" --output "data/Track1/Loc2_4/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_5.mp4" --output "data/Track1/Loc2_5/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_6.mp4" --output "data/Track1/Loc2_6/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_7.mp4" --output "data/Track1/Loc2_7/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc2_8.mp4" --output "data/Track1/Loc2_8/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc3_1.mp4" --output "data/Track1/Loc3_1/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc3_2.mp4" --output "data/Track1/Loc3_2/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc3_3.mp4" --output "data/Track1/Loc3_3/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc3_4.mp4" --output "data/Track1/Loc3_4/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc3_5.mp4" --output "data/Track1/Loc3_5/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc3_6.mp4" --output "data/Track1/Loc3_6/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc4_1.mp4" --output "data/Track1/Loc4_1/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc4_3.mp4" --output "data/Track1/Loc4_3/img"
#python vdo2img.py --input "Track1/track1/track1_videos/Loc4_4.mp4" --output "data/Track1/Loc4_4/img"


python vdo2img.py --input "Track3/track3/Loc1_1.mp4" --output "data/Track3/Loc1_1/img"
python vdo2img.py --input "Track3/track3/Loc1_2.mp4" --output "data/Track3/Loc1_2/img"
python vdo2img.py --input "Track3/track3/Loc1_3.mp4" --output "data/Track3/Loc1_3/img"
python vdo2img.py --input "Track3/track3/Loc1_4.mp4" --output "data/Track3/Loc1_4/img"
python vdo2img.py --input "Track3/track3/Loc2_1.mp4" --output "data/Track3/Loc2_1/img"
python vdo2img.py --input "Track3/track3/Loc2_2.mp4" --output "data/Track3/Loc2_2/img"
python vdo2img.py --input "Track3/track3/Loc2_3.mp4" --output "data/Track3/Loc2_3/img"
python vdo2img.py --input "Track3/track3/Loc2_4.mp4" --output "data/Track3/Loc2_4/img"
python vdo2img.py --input "Track3/track3/Loc2_5.mp4" --output "data/Track3/Loc2_5/img"
python vdo2img.py --input "Track3/track3/Loc2_6.mp4" --output "data/Track3/Loc2_6/img"
python vdo2img.py --input "Track3/track3/Loc3_1.mp4" --output "data/Track3/Loc3_1/img"
python vdo2img.py --input "Track3/track3/Loc3_2.mp4" --output "data/Track3/Loc3_2/img"

# for detection on image directory
#/drives/c/Users/rein9/anaconda3/python mask.py --input "data\Track1\Loc4_4\img" --output "data\Track1\Loc4_4\img" /home/ipl_gpu/Thomas/aicity18/Track1/Loc4_5/detimg1/ /home/ipl_gpu/Thomas/aicity18/Track1/Loc4_5/det.txt .1 .5 0 1799
